### PR TITLE
feat: Adds video "How To Use The App JSON Export/Import Feature"

### PR DESCRIPTION
**Pull request by megaconfidence**
Adds documentation and video guide for "How To Use The App JSON Export/Import Feature"
Video link https://www.youtube.com/watch?v=1YpIzX4DF28

### CODE REVIEW

**Comment by cokoghenun** [comment]
@Pranay105 @jnikhila please review this 🙏

**Comment by jnikhila** [comment]
@cokoghenun - could you please resolve the conflicts and update your branch?

**Comment by Pranay105** [comment]
@cokoghenun there's something wrong with this PR. Can you please pull the main branch again and raise a PR with your changes?

**Comment by cokoghenun** [comment]
@Pranay105 @jnikhila the changes were initially made on the v1.4 branch. Can we just copy the embed URL into `main`?

**Comment by jnikhila** [comment]
@megaconfidence - It looks like there are a lot of branch conflicts, so we are not able to merge this. Could you please raise a ticket - add the video link and doc link for modification? We'll take it from there.

**Pull request closed without merging**
