### PR TITLE
Adding the MongoDB Cloud document.

### PR DESCRIPTION
**Pull request by devbret**

### CODE REVIEW

**Comment by vihar** [comment]
Hey @devbret, thanks for your contribution. Could you also add some lead-in for all these steps?

**Comment by devbret** [comment]
@vihar You are most welcome in terms of my contribution. But I am confused by what you mean when you say "lead-in". Can you please explain what you'd like me to do in more detail? I am happy to make any changes you are interested in having me do.

**Comment by vihar** [comment]
Hey @devbret, lead-in's are basically opening paragraphs before images or screenshots.

 In our case, we could have a paragraph explaining the steps, say for **Navigate to the Network Access screen** step: Select the Network Access Type under the Security Navigation.

**Comment by areyabhishek** [comment]
@vihar @devbret is this ready to be merged in? This is an old PR, so could we merge or close this?

**Comment by vihar** [comment]
We'll be having a new Mongo plugin, It'll be out in the next releases. I think this PR can be closed.

**Review by vihar — APPROVED** [review]

**Pull request merged**
