### PR TITLE
#234 Resolution.

### PR DESCRIPTION
**Pull request by saptarsi96**

### CODE REVIEW

**Comment by hetunandu** [comment]
@saptarsi96 can you explain your contribution here ?

**Comment by saptarsi96** [comment]
@hetunandu I have tried to resolve the issue with extended Markdown #234.
1. The hints have been changed to markdown quotes.
2. The youtube videos are now embedded to display the YouTube Thumbnail which links to the video on YouTube.

**Comment by hetunandu** [comment]
The format is such because we need to support [gitbook](https://www.gitbook.com/)

Please update the PR according to the [contribution guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

**Comment by saptarsi96** [comment]
Sure

**Comment by Nikhil-Nandagopal** [comment]
@saptarsi96 sorry for your time but this is not a valid issue. I request you to please discuss the issue with a maintainer before raising a PR in the future :)

**Pull request closed without merging**
