### PR TITLE
docs: create doc for progressbar widget

### PR DESCRIPTION
**Pull request by techbhavin**
Create document for ProgerssBar widget

### CODE REVIEW

**Review by somangshu — APPROVED** [review]
LGTM

**Comment by dilippitchika** [comment]
@Pranay105 please find the document for progress bar widget - https://www.notion.so/appsmith/Progress-bar-widget-ae7bb93b47414ba9a361fc9acf964f6b

**Comment by Pranay105** [comment]
@dilippitchika, Can you mention the PR for this widget? When is this going live?

**Comment by dilippitchika** [comment]
@Pranay105 
1. Here's the issue for the widget https://github.com/appsmithorg/appsmith/issues/3356 
2. Here's the PR - https://github.com/appsmithorg/appsmith/pull/9574
I'll have to check with @somangshu about the release as we have a bug which we want to resolve. However, it's currently in the release branch.

**Comment by somangshu** [comment]
@dilippitchika we can take up the issue separately, I can say this is going out with the next release. The change we want to make seems backward compatible.

**Review by dilippitchika — COMMENTED** [review]
Updated the documentation

**Review by dilippitchika — APPROVED** [review]

**Pull request closed without merging**
