### PR TITLE
fix: added video caption styles

### PR DESCRIPTION
**Pull request by jnikhila**
to centre align the captions and have font style as italic.

### CODE REVIEW

**Comment by jnikhila** [comment]
@spark-c - Could you please also verify this on different screens?

**Comment by spark-c** [comment]
The centering is not working quite as intended on my end; this is on my Windows machine using Firefox.

image

However, I made a change to `... website/src/components/YoutubeEmbed.js` and now things are centered properly on my end:

```diff
- { caption && <figcaption align="center"><i>{caption}</i></figcaption> }
+ { caption && <figcaption style={{textAlign:"center"}}><i>{caption}</i></figcaption> }
```

image

I'm not sure about why this is the case, it would help to have someone else take a look also!

**Comment by jnikhila** [comment]
> The centering is not working quite as intended on my end; this is on my Windows machine using Firefox.
> 
> image
> 
> However, I made a change to `... website/src/components/YoutubeEmbed.js` and now things are centered properly on my end:
> 
> ```diff
> - { caption && <figcaption align="center"><i>{caption}</i></figcaption> }
> + { caption && <figcaption style={{textAlign:"center"}}><i>{caption}</i></figcaption> }
> ```
> 
> image
> 
> I'm not sure about why this is the case, it would help to have someone else take a look also!

Adding the style attribute wouldn't harm. I'll add and see if that resolves it at your end.

**Comment by jnikhila** [comment]
@spark-c - Do you want to try it again and check?

**Comment by spark-c** [comment]
@jnikhila I just pulled latest, it's looking good on my end 🙂

**Review by spark-c — APPROVED** [review]

**Pull request merged**
