### PR TITLE
feat: Adds video "How To Setup Custom Google Login With Xano"

### PR DESCRIPTION
**Pull request by cokoghenun**
Adds documentation and video guide for "How To Setup Custom Google Login With Xano"
Video link https://www.youtube.com/watch?v=n3XSAA7q--I

### CODE REVIEW

**Comment by cokoghenun** [comment]
Hello

**Comment by cokoghenun** [comment]
Hello

**Comment by cokoghenun** [comment]
@Pranay105 @vihar please review this 🙏

**Comment by cokoghenun** [comment]
@Pranay105 please review this 🙏

**Review by Pranay105 — APPROVED** [review]

**Pull request merged**
