### PR TITLE
docs: Fix grammar in oauth2-authorization-for-google-sheets.md

### PR DESCRIPTION
**Pull request by donno2048**
1. "[...] and **in return**, receive a unique access token **in return**[sic]." - one of the "in return"-s is redundant
2. "Make sure the URL you’re requesting **it**[sic] from the data source." - should be "**is**"
3. "Next, you can use this response and render it **on to**[sic] a table widget on Appsmith" - "on to" and "onto" are **not** the same

### CODE REVIEW

**Comment by donno2048** [comment]
Why did you close this PR? It truly introduced changes that fix grammatical issues, and anyway marking it as spam is really not in place, if this is done because you think I have submitted this PR for the Hacktoberfest challenge then you should know
<details>
<summary>I have completed it without this PR</summary>

image
and I didn't submit it for this purpose, I have enough PRs (not for grammar issues) for hacktoberfest (<a href="https://github.com/makesmatheasy/makesmatheasy/pull/5426">Remove `areaOfCrescentAndLune`</a>, <a href="https://github.com/bridgecrewio/checkov/pull/1718">Fix `dict` verification and more</a>, <a href="https://github.com/MUNComputerScienceSociety/Automata/pull/105">Add Brainf</a>, <a href="https://github.com/ory/dockertest/pull/312">Add compatibility to golang 386</a>, <a href="https://github.com/mattermost/focalboard/pull/1384">Remove default `return`</a> and more)
</details>

The issues I'm referring to are:
1. "[...] and **in return**, receive a unique access token **in return**[sic]." - one of the "in return"-s is redundant
2. "Make sure the URL you’re requesting **it**[sic] from the data source." - should be "**is**"
3. "Next, you can use this response and render it **on to**[sic] a table widget on Appsmith" - "on to" and "onto" are **not** the same

**Comment by donno2048** [comment]
@cokoghenun

**Comment by cokoghenun** [comment]
I closed this because I thought It was for Hacktoberfest (we had a lot of PRs like this). Thanks for your clarification, I'm going to merge this now

**Comment by cokoghenun** [comment]
One more thing, please add a description and update the title of this PR so that the Semantic Pull Request check can pass. You may also need to update your commit messages. Please refer to this guide on how to format your commit messages and PR titles http://udacity.github.io/git-styleguide/

**Comment by donno2048** [comment]
@cokoghenun done

**Comment by cokoghenun** [comment]
Cool. Thanks

**Pull request merged**
