### PR TITLE
15681: Updated Draft (Writing Code | Reactive)

### PR DESCRIPTION
**Pull request by spark-c**
Content amends "Reactive" section of docs page Core Concepts > Writing Code, found [here](https://docs.appsmith.com/core-concepts/writing-code#reactive).

Commit reflects requested changes from previous review.

Original ticket found [here](https://github.com/appsmithorg/appsmith/issues/15681).

### CODE REVIEW

**Comment by Pranay105** [comment]
The content is good. The tab and select widget example is confusing. I'll suggest you to use a better example.

**Comment by jnikhila** [comment]
@ohansFavour - Could you please verify the changes from a tech standpoint?

**Comment by ohansFavour** [comment]
@jnikhila This looks good ✈️

**Comment by Pranay105** [comment]
Looks good to me now. Great example! @spark-c  you can move it to Gitbook now!

**Review by Pranay105 — APPROVED** [review]

**Pull request merged**
