### PR TITLE
Hacktoberfest - Fixed grammar and improved sentences

### PR DESCRIPTION
**Pull request by mikidoodle**
Hey!
I’ve fixed some grammar mistakes and improved on the framing of the sentences.
Have a great day!

### CODE REVIEW

**Comment by vihar** [comment]
Hey @mikidoodle , thanks for raising the PRs, we will review them shortly. Please note that these will not be considered for Hacktoberfest. To contribute towards Hacktoberfest, please refer to this issue: https://github.com/appsmithorg/appsmith-docs/issues/244

**Comment by mikidoodle** [comment]
Hello @vihar, thank you for replying. It’s alright if its not counted for Hacktoberfest. How are the PRs counted in [https://hacktoberfest.appsmith.com/](AppSmith’s Hacktoberfest challenge)? Is it from the total PRs you get approved, or only contributions to AppSmith’s repositories?

**Comment by vihar** [comment]
Hey @mikidoodle, we count PRs based on contributions made to Appsmith repos. It can be either documentation or our main [repository](https://github.com/appsmithorg/appsmith).

**Comment by mikidoodle** [comment]
Hello @vihar. I actually don’t understand why this will not count towards hacktoberfest. Could you please explain?
Thanks.

**Comment by mikidoodle** [comment]
Thank you @vihar!

**Comment by mikidoodle** [comment]
:(

**Pull request closed without merging**
