### PR TITLE
fix: added reset password section to auth page

### PR DESCRIPTION
**Pull request by spark-c**
Resolves [appsmithorg/appsmith-docs#16042](https://github.com/appsmithorg/appsmith/issues/16042).

### CODE REVIEW

**Comment by jnikhila** [comment]
@spark-c - the reset password section doesn't fit in the authentication landing page. Do you think we can add it to some other page? The issue talks about email page. Also, could you please add a screenshot for the reset password link?

**Comment by spark-c** [comment]
@jnikhila Sure, I'll move it to the email page as the ticket mentioned; I had initially put it in the Auth page since it's related to user sign-in methods, and email is just a prerequisite but not as related topically. I'll put a screenshot in as well

**Comment by jnikhila** [comment]
> @jnikhila Sure, I'll move it to the email page as the ticket mentioned; I had initially put it in the Auth page since it's related to user sign-in methods, and email is just a prerequisite but not as related topically. I'll put a screenshot in as well

Let's discuss this in standup, before you make any changes.

**Comment by danciaclara** [comment]
> > @jnikhila Sure, I'll move it to the email page as the ticket mentioned; I had initially put it in the Auth page since it's related to user sign-in methods, and email is just a prerequisite but not as related topically. I'll put a screenshot in as well.
> 
> Let's discuss this in standup before you make any changes. Update: As discussed, let's add it to the [Troubleshooting Guide - Application Errors - Reset Password](https://docs.appsmith.com/help-and-support/troubleshooting-guide/application-errors#reset-password-error) Section.

I think this should be under Authentication -> Email under a subheading called - **Reset email password**

**Comment by jnikhila** [comment]
> > > @jnikhila Sure, I'll move it to the email page as the ticket mentioned; I had initially put it in the Auth page since it's related to user sign-in methods, and email is just a prerequisite but not as related topically. I'll put a screenshot in as well.
> > 
> > 
> > Let's discuss this in standup before you make any changes. Update: As discussed, let's add it to the [Troubleshooting Guide - Application Errors - Reset Password](https://docs.appsmith.com/help-and-support/troubleshooting-guide/application-errors#reset-password-error) Section.
> 
> I think this should be under Authentication -> Email under a subheading called - **Reset password**

@danciaclara - Authentication doesn't have a sub-page Email. Are you referring to Instance Configuration -> Email.

**Comment by spark-c** [comment]
Note after discussion:
- Add callout on Email page to let Admins know to set up email in case users need to reset passwords in the future
- In the future, may add a cross-reference on another page to this content on the Troubleshooting page.

**Comment by spark-c** [comment]
Note: linter fixes for the Email page are contained in a different PR that was raised to fix a formatting issue on the page.

**Review by danciaclara — APPROVED** [review]

**Review by jnikhila — APPROVED** [review]

**Comment by jnikhila** [comment]
@danciaclara - Shouldn't the guide follow the cause/error and solution format? Also, the file has conflicts that would need to be fixed.

**Review by jnikhila — APPROVED** [review]

**Review by danciaclara — APPROVED** [review]

**Pull request merged**
