### PR TITLE
feat: Adds video "How To Build CRUD Apps With Airtable"

### PR DESCRIPTION
**Pull request by megaconfidence**
Adds documentation and video guide for "How To Build CRUD Apps With Airtable"
Video link https://www.youtube.com/watch?v=cmr2-SsBR3w

### CODE REVIEW

**Comment by cokoghenun** [comment]
@Pranay105 @jnikhila please review this 🙏

**Comment by Pranay105** [comment]
@cokoghenun Please create a PR for `main` branch from now on. v1.4 is not the deployed branch anymore.

**Comment by jnikhila** [comment]
@Pranay105 - Have we added this to the main branch?

**Comment by Pranay105** [comment]
@jnikhila - No, will add this today.

**Comment by cokoghenun** [comment]
I've updated the base branch to main

**Comment by jnikhila** [comment]
@megaconfidence - There are a lot of merge conflicts. Could you please raise a ticket with doc link and updated video, and we'll take it from there.

**Pull request closed without merging**
