### PR TITLE
fix: feedback widget design changes

### PR DESCRIPTION
**Pull request by jnikhila**
- updated the widget to be added to the footer
- updated designs

## Checklist
I have:
- [ ] run the content through Grammarly
- [ ] linked to sample apps when relevant
- [ ] added the meta description for each page in the PR
- [ ] minimized the callouts and added only when necessary
- [ ] added the `queryString` parameter to the Tabs (if used)
- [ ] masked PII in images. For example, login credentials, account details, and more
- [ ] added images only when necessary
- [ ] deleted the images that are no longer used for the updated pages in the PR
- [ ] followed the image file naming convention while renaming or adding new images. (Use lowercase letters, dashes between words, and be as descriptive as possible)
- [ ] used the `<figure/>` tag instead of a markdown representation for images
- [ ] added the `<figcaption/>` tag to add a caption to the image
- [ ] added the `alt` attribute in the `` tag
- [ ] verified and updated the cross-references or created redirect rules for the changed or removed content 
- [ ] reviewed and applied the style changes for UI formatting. For example, Bold the UI elements(Buttons on screen) used in the doc.

### CODE REVIEW

**Review by danciaclara — DISMISSED** [review]

**Comment by vasanthappsmith** [comment]
Screenshot 2023-09-18 at 6 34 29 PM

Icon Button missing the states, Default, Hover, Active, Focus. 
Icon button as a whole is not have cursor to Pointer. Only the icon is having currently. 


Heading: "Was this page helpful?"

color: var(--colors-ui-content-heading-section-heading, #364252);
font-family: SF Pro Display;
font-size: 20px;
font-style: normal;
font-weight: 500;
line-height: 125%;

**Comment by jnikhila** [comment]
> Screenshot 2023-09-18 at 6 34 29 PM
> Icon Button missing the states, Default, Hover, Active, Focus. Icon button as a whole is not have cursor to Pointer. Only the icon is having currently.
> 
> Heading: "Was this page helpful?"
> 
> color: var(--colors-ui-content-heading-section-heading, #364252); font-family: SF Pro Display; font-size: 20px; font-style: normal; font-weight: 500; line-height: 125%;

- We are using the font family that is used across doc pages. 
- I'll fix the cursor for the icon button.

**Comment by jnikhila** [comment]
> > Screenshot 2023-09-18 at 6 34 29 PM
> > Icon Button missing the states, Default, Hover, Active, Focus. Icon button as a whole is not have cursor to Pointer. Only the icon is having currently.
> > Heading: "Was this page helpful?"
> > color: var(--colors-ui-content-heading-section-heading, #364252); font-family: SF Pro Display; font-size: 20px; font-style: normal; font-weight: 500; line-height: 125%;
> 
> * We are using the font family that is used across doc pages.
> * I'll fix the cursor for the icon button.

Added hover styles. The active or clicked states will not be visible as a thank you message is shown to the users.

**Comment by vasanthappsmith** [comment]
@jnikhila This looks good!

**Comment by jnikhila** [comment]
Please approve the PR. @vasanthappsmith

**Review by vasanthappsmith — APPROVED** [review]

**Pull request merged**
