### PR TITLE
feat: Only Date Option

### PR DESCRIPTION
**Pull request by wmdev0808**
-- Add new entries for isTimeEnabled, dateTimeFormat properties

### CODE REVIEW

**Comment by Pranay105** [comment]
Hi @wmdev0808, can you mention the issue so I can check the status of this? For now, I don't see this property live or even in prod.

**Comment by wmdev0808** [comment]
> Hi @wmdev0808, can you mention the issue so I can check the status of this? For now, I don't see this property live or even in prod.

The PR for this issue has not merged into release yet

**Comment by Pranay105** [comment]
Okay, thanks. Can you just mention the PR for such issues so that the documentation can be in sync with the updates?

**Comment by wmdev0808** [comment]
https://github.com/appsmithorg/appsmith/issues/3516

**Pull request closed without merging**
