### PR TITLE
feat: Adds video "How to use Custom Branding"

### PR DESCRIPTION
**Pull request by megaconfidence**
Adds documentation and video guide for "How to use Custom Branding"
Video link https://www.youtube.com/watch?v=E_4I0J-0u1k

### CODE REVIEW

**Comment by megaconfidence** [comment]
@Pranay105 @jnikhila please review this 🙏

**Comment by danciaclara** [comment]
@megaconfidence can you pull the latest from main. we the video on another PR https://docs.appsmith.com/advanced-concepts/branding. maybe this should be moved a bit to the top?

**Comment by jnikhila** [comment]
@megaconfidence - We replaced the documentation video with the custom branding video because having both videos was like repetition, and it is already available on [docs.appsmith.com](https://docs.appsmith.com/advanced-concepts/branding). Please let me know if you have different views.

**Review by danciaclara — APPROVED** [review]

**Comment by megaconfidence** [comment]
Thanks for letting me know @jnikhila . LGTM!

**Pull request merged**
