### PR TITLE
fix: Git Multiple Environments in Community Edition

### PR DESCRIPTION
**Pull request by infinitetrooper**
@jnikhila - I added the points in 3 steps. I'm still trying to find another word for environments as I don't want people to land here when they search for Multiple Environments.

It needs hyperlinking and improving language but, the overall process is there to make progress on that aspect.

### CODE REVIEW

**Comment by jnikhila** [comment]
> @jnikhila - I added the points in 3 steps. I'm still trying to find another word for environments as I don't want people to land here when they search for Multiple Environments.
> 
> It needs hyperlinking and improving language but, the overall process is there to make progress on that aspect.

@infinitetrooper - Do you think Pipeline can be used in place of environments?

**Comment by jnikhila** [comment]
@infinitetrooper - The draft looks good. We can take it ahead and make the necessary changes. Thanks for your quick help here.

**Comment by infinitetrooper** [comment]
> > @jnikhila - I added the points in 3 steps. I'm still trying to find another word for environments as I don't want people to land here when they search for Multiple Environments.
> > It needs hyperlinking and improving language but, the overall process is there to make progress on that aspect.
> 
> @infinitetrooper - Do you think Pipeline can be used in place of environments?

@jnikhila  - I made some changes in the last commit, may be this fits better. Made the focus completely on Git.

**Comment by infinitetrooper** [comment]
> @infinitetrooper - The draft looks good. We can take it ahead and make the necessary changes. Thanks for your quick help here.

Great, please add me as a reviewer at the end, want to check it with the Git team as well. Thanks.

**Comment by danciaclara** [comment]
Added via https://github.com/appsmithorg/appsmith-docs/pull/1069

**Pull request closed without merging**
