### PR TITLE
feat: multi-line input

### PR DESCRIPTION
**Pull request by harshilp24**

### CODE REVIEW

**Comment by danciaclara** [comment]
@harshilp24 could you link the relevant issue under Development?

**Comment by harshilp24** [comment]
> @harshilp24 could you link the relevant issue under Development? Thanks

done @danciaclara

**Review by somangshu — APPROVED** [review]

**Review by danciaclara — APPROVED** [review]

**Comment by jnikhila** [comment]
@riodeuno - Please take a look and let us know if anything is missing.

**Review by riodeuno — APPROVED** [review]

**Comment by riodeuno** [comment]
@jnikhila Looks good to me.

**Pull request merged**
