### PR TITLE
update README.md file and edited demo video URL

### PR DESCRIPTION
**Pull request by sohamsshah**
Changes:
* Minor changes in the grammar and sentence framing
* Fix and provided a link to the youtube demo video on the last line of the README.md file.

### CODE REVIEW

**Comment by Nikhil-Nandagopal** [comment]
@sohamsshah this PR is invalid, updated the issue

**Comment by sohamsshah** [comment]
@Nikhil-Nandagopal No problem. But please remove the invalid tag if possible, as in hacktoberfest2020 it will be counted as spam and I may get disqualified for the fest. I genuinely didnt wanted to do spamming. Thank you.

**Comment by sohamsshah** [comment]
@Nikhil-Nandagopal I apologize for not discussing with the maintainers. Will take care in future, but just don't want to get disqualified 😁 I hope you understand.

**Comment by Nikhil-Nandagopal** [comment]
@sohamsshah don't worry you won't be discounted unless you open multiple spam PRs. Invalid will only ensure that this PR is not counted for hacktober

**Comment by sohamsshah** [comment]
Okay Cool. Thanks

**Pull request closed without merging**
